<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\BarangInventori;
use App\Models\ProdukKebersihan;

class BarangInventoriSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'nama_barang' => 'Bayclin 1L',
                'kode_barang' => '19',
                'produk_id' => 19,
                'satuan' => 'Botol',
                'stok_saat_ini' => 4,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/0oNkyOsQ3oV7vPPJscVpLKrVsS2tkAtX4nLmbwmt.jpg',
                'deskripsi' => 'Cairan pemutih dan disinfektan untuk membersihkan serta menghilangkan noda dan kuman pada permukaan maupun pakaian.',
            ],
            [
                'nama_barang' => 'Baygon 600mL',
                'kode_barang' => '17',
                'produk_id' => 17,
                'satuan' => 'Kaleng',
                'stok_saat_ini' => 22,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/DdR2EcPPjCkljdum257owqu3vEBsXz8nCxCu2D8P.jpg',
                'deskripsi' => 'Cairan/semprotan pembasmi serangga seperti nyamuk, lalat, dan kecoa.',
            ],
            [
                'nama_barang' => 'Botol Pump Hand Soap',
                'kode_barang' => '47',
                'produk_id' => 46,
                'satuan' => 'botol',
                'stok_saat_ini' => 7,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/C49rssa1JyNeGOTyCIZyCVEdNDTR32FQ40xSh0rg.jpg',
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Botol Sprayer',
                'kode_barang' => '33',
                'produk_id' => 33,
                'satuan' => 'botol',
                'stok_saat_ini' => 9,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/oEJLTgfkQaK0NNsHTZKXPl8tj4KmJ3YSJxmJnIwV.jpg',
                'deskripsi' => 'Botol semprot untuk menyimpan dan menyemprotkan cairan pembersih.',
            ],
            [
                'nama_barang' => 'Bowl Cleaner (Pembersih Kaca)',
                'kode_barang' => '5',
                'produk_id' => 5,
                'satuan' => 'galon',
                'stok_saat_ini' => 14,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Buffing Fad 3 M Merah 16\'',
                'kode_barang' => '39',
                'produk_id' => 38,
                'satuan' => 'buah',
                'stok_saat_ini' => 2,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/eQgLn5iouCEYWAp6iG6ZRQ2nPVXzaOtm7gCqDymt.jpg',
                'deskripsi' => 'Pad mesin poles untuk membersihkan lantai dengan tingkat abrasif sedang.',
            ],
            [
                'nama_barang' => 'Buffing Fad 3 M Putih 16\'',
                'kode_barang' => '40',
                'produk_id' => 39,
                'satuan' => 'buah',
                'stok_saat_ini' => 3,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/iLw84ZDl9dKpdnfK3JZI78ddy4S2b9ppg9mRpQYi.jpg',
                'deskripsi' => 'Pad mesin poles untuk mengilapkan lantai tanpa merusak lapisan finishing.',
            ],
            [
                'nama_barang' => 'Celemek',
                'kode_barang' => '52',
                'produk_id' => 51,
                'satuan' => 'buah',
                'stok_saat_ini' => 4,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/pXdATuFbfSNA0QFwQsvqbe30GXtorsbHs1jeY3XE.jpg',
                'deskripsi' => 'Pelindung pakaian petugas saat melakukan pekerjaan kebersihan.',
            ],
            [
                'nama_barang' => 'Detergen Rinso 46gr',
                'kode_barang' => '7',
                'produk_id' => 7,
                'satuan' => 'bungkus',
                'stok_saat_ini' => 114,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/1aIOmdLqaoavhlofww5MFSFhDRrSxUC8mDuocZT2.jpg',
                'deskripsi' => 'Deterjen bubuk untuk mencuci kain lap, mop, atau perlengkapan berbahan kain.',
            ],
            [
                'nama_barang' => 'Ember Plastik',
                'kode_barang' => '50',
                'produk_id' => 49,
                'satuan' => 'buah',
                'stok_saat_ini' => 5,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/8K7bklESS06exdrffAzgrgMC1oYcoXx7QOALbvCG.jpg',
                'deskripsi' => 'Wadah untuk menampung air atau larutan pembersih.',
            ],
            [
                'nama_barang' => 'Filter masker respirator',
                'kode_barang' => '56',
                'produk_id' => 55,
                'satuan' => 'buah',
                'stok_saat_ini' => 60,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/G9wtRq55xtnnqTESu1J5cH6pfmYLaZIV0pbJzCz8.jpg',
                'deskripsi' => 'Filter pengganti respirator untuk menyaring debu dan partikel berbahaya.',
            ],
            [
                'nama_barang' => 'Floor Cleaner (Pembersih Lantai)',
                'kode_barang' => '1',
                'produk_id' => 1,
                'satuan' => 'galon',
                'stok_saat_ini' => 10,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Frame Lobby Duster',
                'kode_barang' => '58',
                'produk_id' => 57,
                'satuan' => 'buah',
                'stok_saat_ini' => 8,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Gagang Pel',
                'kode_barang' => '42',
                'produk_id' => 41,
                'satuan' => 'buah',
                'stok_saat_ini' => 3,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/YLkzOe5c3z268eQyBkodz7ewzGfYmPrAaFUaAUN9.jpg',
                'deskripsi' => 'Tongkat pegangan untuk kain pel atau mop.',
            ],
            [
                'nama_barang' => 'Gayung',
                'kode_barang' => '61',
                'produk_id' => 60,
                'satuan' => 'buah',
                'stok_saat_ini' => 5,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Glass Cleaner',
                'kode_barang' => '6',
                'produk_id' => 6,
                'satuan' => 'galon',
                'stok_saat_ini' => 6,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/3EHk2rbkfUAaO3dIhO9LuxpBSkp1XQBEfVVRXdgj.jpg',
                'deskripsi' => 'Cairan pembersih kaca agar bebas noda dan bekas sidik jari.',
            ],
            [
                'nama_barang' => 'Kain Lap Kanebo',
                'kode_barang' => '14',
                'produk_id' => 14,
                'satuan' => 'buah',
                'stok_saat_ini' => 22,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Kain Lap Kotak-kotak Brutop',
                'kode_barang' => '32',
                'produk_id' => 32,
                'satuan' => 'buah',
                'stok_saat_ini' => 4,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Kain Lobby Duster',
                'kode_barang' => '36',
                'produk_id' => 36,
                'satuan' => 'buah',
                'stok_saat_ini' => 14,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Kain Microfiber',
                'kode_barang' => '53',
                'produk_id' => 52,
                'satuan' => 'buah',
                'stok_saat_ini' => 30,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Kain Pel Biru',
                'kode_barang' => '45',
                'produk_id' => 44,
                'satuan' => 'buah',
                'stok_saat_ini' => 4,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/zkqFNyB1mdNs1ctBb8krdSqe6lRs4chml33ytfky.jpg',
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Kain Pel Merah',
                'kode_barang' => '44',
                'produk_id' => 43,
                'satuan' => 'buah',
                'stok_saat_ini' => 5,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/UM7iDLcWUHVdvsOxYCKy2gq1FYhqdR5TmUNBfyXi.jpg',
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Kamper Bola Pingpong',
                'kode_barang' => '48',
                'produk_id' => 47,
                'satuan' => 'pak',
                'stok_saat_ini' => 0,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Kamper Bola Tenis',
                'kode_barang' => '10',
                'produk_id' => 10,
                'satuan' => 'buah',
                'stok_saat_ini' => 0,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Kape Kayu',
                'kode_barang' => '64',
                'produk_id' => 63,
                'satuan' => 'buah',
                'stok_saat_ini' => 0,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Karbol Wangi',
                'kode_barang' => '4',
                'produk_id' => 4,
                'satuan' => 'galon',
                'stok_saat_ini' => 13,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Keset Toilet 40x60',
                'kode_barang' => '62',
                'produk_id' => 61,
                'satuan' => 'buah',
                'stok_saat_ini' => 0,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Kispray',
                'kode_barang' => '16',
                'produk_id' => 16,
                'satuan' => 'pouch',
                'stok_saat_ini' => 3,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/IWqYPkiuJP210MuJigvQ4jhMDQ2bWQFAvVx3YFmn.jpg',
                'deskripsi' => 'Cairan pewangi dan pelicin pakaian setelah dicuci.',
            ],
            [
                'nama_barang' => 'Kuas Pembersih Keyboard',
                'kode_barang' => '65',
                'produk_id' => 64,
                'satuan' => 'buah',
                'stok_saat_ini' => 15,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Masker Respirator',
                'kode_barang' => '55',
                'produk_id' => 54,
                'satuan' => 'buah',
                'stok_saat_ini' => 1,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Matic Spray 1set',
                'kode_barang' => '63',
                'produk_id' => 62,
                'satuan' => 'buah',
                'stok_saat_ini' => 0,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Pembersih Kaca',
                'kode_barang' => 'PKC-001',
                'produk_id' => null,
                'satuan' => 'botol',
                'stok_saat_ini' => 5,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/PNCxZUYVa7RqGl1QrUZ7Mk5cSyp80J1dBk3aUY7P.jpg',
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Pengki Plastik',
                'kode_barang' => '30',
                'produk_id' => 30,
                'satuan' => 'buah',
                'stok_saat_ini' => 6,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Plastik Hitam 50 x 75',
                'kode_barang' => '20',
                'produk_id' => 20,
                'satuan' => 'pak',
                'stok_saat_ini' => 40,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Plastik Hitam 60 x 100',
                'kode_barang' => '21',
                'produk_id' => 21,
                'satuan' => 'pak',
                'stok_saat_ini' => 57,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Plastik Kresek Hitam Uk 35',
                'kode_barang' => '23',
                'produk_id' => 23,
                'satuan' => 'pak',
                'stok_saat_ini' => 80,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Plastik Kresek Kuning Uk 35',
                'kode_barang' => '24',
                'produk_id' => 24,
                'satuan' => 'pak',
                'stok_saat_ini' => 65,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Plastik Kuning Uk 60 x 100',
                'kode_barang' => '22',
                'produk_id' => 22,
                'satuan' => 'pak',
                'stok_saat_ini' => 29,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Plastik Mop Holder',
                'kode_barang' => '18',
                'produk_id' => 18,
                'satuan' => 'buah',
                'stok_saat_ini' => 6,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Pledge Spray',
                'kode_barang' => '8',
                'produk_id' => 8,
                'satuan' => 'botol',
                'stok_saat_ini' => 0,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/1d7O0tJcUJWaVxW3lFI0ByZMiuBjv6w7N9fjVqYR.jpg',
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Rinso Matic Cair 4,5 L',
                'kode_barang' => '60',
                'produk_id' => 59,
                'satuan' => 'galon',
                'stok_saat_ini' => 7,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/EJjrDRFgmv4zc4dn83XSoDCtZuQYazlyHJ9HTRSh.jpg',
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Sabun Cream Ekonomi',
                'kode_barang' => '37',
                'produk_id' => 37,
                'satuan' => 'bungkus',
                'stok_saat_ini' => 0,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/ve1w0Mi8GWfgkMCKt1MLSIJQy0vT4i5MFzFR7BkO.jpg',
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Sabun Cuci Piring',
                'kode_barang' => '3',
                'produk_id' => 3,
                'satuan' => 'galon',
                'stok_saat_ini' => 19,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Sabun Cuci Tangan (Handsoap)',
                'kode_barang' => '2',
                'produk_id' => 2,
                'satuan' => 'galon',
                'stok_saat_ini' => 17,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Sapu Ijuk',
                'kode_barang' => null,
                'produk_id' => null,
                'satuan' => 'pcs',
                'stok_saat_ini' => 10,
                'stok_minimum' => 2,
                'foto_barang' => 'barang/kORW4z3Nme3DQNXHckMIWddUuFbiTokPOtJbXIcC.jpg',
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Sapu Lidi',
                'kode_barang' => '35',
                'produk_id' => 35,
                'satuan' => 'buah',
                'stok_saat_ini' => 4,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Sarung Tangan Karet',
                'kode_barang' => '49',
                'produk_id' => 48,
                'satuan' => 'pasang',
                'stok_saat_ini' => 4,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/AnV5KPmNKSLR3EEzVLFS3eZmsjnhjFlPxSU3i5Fr.jpg',
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Sikat gagang panjang',
                'kode_barang' => '43',
                'produk_id' => 42,
                'satuan' => 'buah',
                'stok_saat_ini' => 3,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/4nSIi1j5qFHbDUKeVFQbnYoda6EuVZDIsQXywC8m.jpg',
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Sikat Tangan Gagang Nagata',
                'kode_barang' => '9',
                'produk_id' => 9,
                'satuan' => 'buah',
                'stok_saat_ini' => 12,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/tVnlXmlemHqXsMKPuNJf8dW5AAUrdBjPWGfxyUHz.jpg',
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Sikat WC Bulat',
                'kode_barang' => '46',
                'produk_id' => 45,
                'satuan' => 'buah',
                'stok_saat_ini' => 17,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/WP7WcBGgIOg4DgRu0UwjL6JffMJ6NYiM53DXySqb.jpg',
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'SOS Pembersih lantai 4L',
                'kode_barang' => '54',
                'produk_id' => 53,
                'satuan' => 'galon',
                'stok_saat_ini' => 0,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Stella AC Gantung',
                'kode_barang' => '15',
                'produk_id' => 15,
                'satuan' => 'buah',
                'stok_saat_ini' => 79,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Stella Matic Refill',
                'kode_barang' => '11',
                'produk_id' => 11,
                'satuan' => 'kaleng',
                'stok_saat_ini' => 68,
                'stok_minimum' => 5,
                'foto_barang' => 'barang/T91Mll9WqyGAiAOFFzneAuGhcp7urO7rymWuAKEI.jpg',
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Tapas Gagang',
                'kode_barang' => '13',
                'produk_id' => 13,
                'satuan' => 'buah',
                'stok_saat_ini' => 9,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Tapas Hijau',
                'kode_barang' => '28',
                'produk_id' => 28,
                'satuan' => 'buah',
                'stok_saat_ini' => 55,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Tapas Merah',
                'kode_barang' => '66',
                'produk_id' => 65,
                'satuan' => 'buah',
                'stok_saat_ini' => 8,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Tapas Sponge Politex',
                'kode_barang' => '12',
                'produk_id' => 12,
                'satuan' => 'buah',
                'stok_saat_ini' => 24,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Tissu Hand Towel/24',
                'kode_barang' => '27',
                'produk_id' => 27,
                'satuan' => 'pak',
                'stok_saat_ini' => 271,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Tissu Kotak',
                'kode_barang' => '29',
                'produk_id' => 29,
                'satuan' => 'pak',
                'stok_saat_ini' => 7,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Tissu Roll (Kecil)',
                'kode_barang' => '25',
                'produk_id' => 25,
                'satuan' => 'roll',
                'stok_saat_ini' => 663,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Tissu Toilet (Besar)',
                'kode_barang' => '26',
                'produk_id' => 26,
                'satuan' => 'roll',
                'stok_saat_ini' => 0,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Tissu Wajah',
                'kode_barang' => '41',
                'produk_id' => 40,
                'satuan' => 'pak',
                'stok_saat_ini' => 0,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Vanish 750 ml',
                'kode_barang' => '57',
                'produk_id' => 56,
                'satuan' => 'pouch',
                'stok_saat_ini' => 29,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Wet Floor Sign',
                'kode_barang' => '51',
                'produk_id' => 50,
                'satuan' => 'buah',
                'stok_saat_ini' => 8,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Wifer Kaca',
                'kode_barang' => '59',
                'produk_id' => 58,
                'satuan' => 'buah',
                'stok_saat_ini' => 8,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
            [
                'nama_barang' => 'Wifer Lantai Dragon',
                'kode_barang' => '31',
                'produk_id' => 31,
                'satuan' => 'buah',
                'stok_saat_ini' => 9,
                'stok_minimum' => 5,
                'foto_barang' => null,
                'deskripsi' => null,
            ],
        ];

        foreach ($data as $item) {
            BarangInventori::updateOrCreate(
                ['nama_barang' => $item['nama_barang']],
                $item
            );
        }
    }
}
